<?php

namespace Libraries;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-09 at 19:43:09.
 */
class AuthenticationTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Authentication
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Authentication;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Libraries\Authentication::verify
     */
    public function testVerify() {
        $password = '$2y$10$VUpNcC1NSFlqSDE1Yy9qb.ggUFNoLQhSE9PpsqQWuvXwh8EA7zM..';
        $this->assertTrue( $this->object->verify('test', $password));
    }
    
    /**
     * @depends testVerify
     * @covers Libraries\Authentication::generate
     */
    public function testGenerate() {
        $password  = $this->object->generate('test');
        $this->assertTrue( $this->object->verify('test', $password) );
    }
}
