<?php

namespace Libraries;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-09 at 21:22:13.
 */
class ClassLoaderTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ClassLoader
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ClassLoader;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Libraries\ClassLoader::load
     */
    public function testLoad() {
        
        $className = 'Libraries\\Image';
        $this->object->load($className);
        
        $this->assertTrue( class_exists('Libraries\\Image'));
        
    }

    /**
     * @covers Libraries\ClassLoader::register
     */
    public function testRegister() {
                
        $this->object->register();
        
        $autoloadFunctions = spl_autoload_functions();
        $last = count($autoloadFunctions) - 1;
                
        $loader = $autoloadFunctions[$last];
        
        $this->assertTrue( $loader[1] === 'load' && $loader[0] == $this->object );
    }

}
