<?php

namespace Libraries;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-02-12 at 16:14:58.
 */
class IoCTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var IoC
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IoC;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Libraries\IoC::register
     * @todo   Implement testRegister().
     */
    public function testRegister()
    {

    }

    /**
     * @covers Libraries\IoC::singleton
     * @todo   Implement testSingleton().
     */
    public function testSingleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Libraries\IoC::resolve
     * @todo   Implement testResolve().
     */
    public function testResolve()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Libraries\IoC::registered
     * @todo   Implement testRegistered().
     */
    public function testRegistered()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
